# Global settings for sources and sinks (connectors). These can be overridden
# in flows.yaml.
# Each connector has a Scaladoc entry detailing its configuration. You can find
# listings of the entries at
# https://wanduow.github.io/streamevmon/nz/net/wand/streamevmon/flink/sources/index.html
# and
# https://wanduow.github.io/streamevmon/nz/net/wand/streamevmon/flink/sinks/index.html

source:
  postgres:
    servername: localhost
    portNumber: 5432
    databaseName: nntsc
    user: cuz
    password: ""
    tracerouteRefreshDelay: 600

  # One of each of the following MUST be set by the user for influx sources to function:
  # influx.subscriptionName, or influx.<type>.subscriptionName

  # The following MAY be set to override the value determined at runtime:
  # influx.listenAddress, or influx.<type>.listenAddress
  influx:
    serverName: localhost
    portNumber: 8086
    historicalQueryProtocol: http
    compressHistoricalQueries: false
    listenProtocol: http
    listenPort: 0
    listenBacklog: 30
    retentionPolicy: autogen
    amp:
      user: cuz
      password: ""
      databaseName: nntsc
      retentionPolicy: nntscdefault
    bigdata:
      user: bigdata
      password: bigdata
      databaseName: bigdata

  esmond:
    # serverName: http://denv-owamp.es.net:8085  # MUST be set by user
    fetchHistory: 86400
    discoverTimeRange: 86400
    timeOffset: 0
    targetRefreshInterval: 600
    minimumTimeBetweenQueries: 1
    # The following keys MAY (but many probably SHOULD) be set by the user.
    # limit: 0
    # offset: 0
    # source: denv-owamp.es.net
    # destination: bois-owamp.es.net
    # measurementAgent: denv-owamp.es.net
    # toolName: pscheduler/powstream
    # dnsMatchRule: v4v6
    # eventType: packet-loss-rate
    # summaryType: aggregation
    # summaryWindow: 300

  latencyts:
    ampicmp:
      location: /usr/share/flink/data/latency-ts-i/ampicmp/series
      files: "*"
    smokeping:
      location: /usr/share/flink/data/latency-ts-i/smokeping/series
      files: "*"

  nab:
    location: /usr/share/flink/data/NAB/data

sink:
  influx:
    databaseName: streamevmon
    retentionPolicy: streamevmondefault
    user: cuz
    password: ""
