# Global settings for detectors. These can be overridden in flows.yaml.
# See the Scaladoc entries for the package objects (on the right side) at
# https://wanduow.github.io/streamevmon/nz/net/wand/streamevmon/detectors/index.html
# for details on configuring each detector.

detector:
  # We use YAML anchors in this file since there are a number of shared settings
  # that apply to all detectors.
  default: &timeWindowWrapperSettings
    useFlinkTimeWindow: true
    windowDuration: 60
    windowSize: 50
    windowSlide: 1

  baseline:
    - *timeWindowWrapperSettings
    - inactivityPurgeTime: 600
    - maxHistory: 50
    - percentile: 0.10
    - threshold: 25

  changepoint:
    - *timeWindowWrapperSettings
    - maxHistory: 60
    - triggerCount: 40
    - ignoreOutlierNormalCount: 1
    - inactivityPurgeTime: 60
    - minimumEventInterval: 10
    - severityThreshold: 30

  distdiff:
    - *timeWindowWrapperSettings
    - recentsCount: 20
    - minimumChange: 1.05
    - zThreshold: 5.0
    - dropExtremeN: 2
    - inactivityPurgeTime: 1200

  loss:
    - *timeWindowWrapperSettings
    - maxHistory: 30
    - lossCount: 10
    - consecutiveCount: 5

  mode:
    - *timeWindowWrapperSettings
    - maxHistory: 30
    - minFrequency: 6
    - minProminence: 3
    - threshold: 7.5
    - inactivityPurgeTime: 60

  spike:
    - *timeWindowWrapperSettings
    - inactivityPurgeTime: 60
    - lag: 50
    - threshold: 50
    - influence: 0.01
