detector:
  default: &timeWindowWrapperSettings
    useFlinkTimeWindow: true
    windowDuration: 60
    windowSize: 50
    windowSlide: 1

  baseline:
    - *timeWindowWrapperSettings
    - inactivityPurgeTime: 600
    - maxHistory: 50
    - percentile: 0.10
    - threshold: 25

  changepoint:
    - *timeWindowWrapperSettings
    - maxHistory: 60
    - triggerCount: 40
    - ignoreOutlierNormalCount: 1
    - inactivityPurgeTime: 60
    - minimumEventInterval: 10
    - severityThreshold: 30

  distdiff:
    - *timeWindowWrapperSettings
    - recentsCount: 20
    - minimumChange: 1.05
    - zThreshold: 5.0
    - dropExtremeN: 2
    - inactivityPurgeTime: 1200

  loss:
    - *timeWindowWrapperSettings
    - maxHistory: 30
    - lossCount: 10
    - consecutiveCount: 5

  mode:
    - *timeWindowWrapperSettings
    - maxHistory: 30
    - minFrequency: 6
    - minProminence: 3
    - threshold: 7.5
    - inactivityPurgeTime: 60

  spike:
    - *timeWindowWrapperSettings
    - inactivityPurgeTime: 60
    - lag: 50
    - threshold: 50
    - influence: 0.01
