defaultFlowSinks: &allSinks
  influx: true
  print: true

flows:
  influx:
    amp:
      icmp:
        filterLossy:
          baseline:
            *allSinks
          changepoint:
            *allSinks
          distdiff:
            *allSinks
          mode:
            *allSinks
          spike:
            *allSinks
          notADetector:
            *allSinks
      dns:
        loss:
          *allSinks
      notAType:
        loss:
          *allSinks

