defaultFlowSinks: &allSinks
  influx: true
  print: true

flows:
  influx:
    amp:
      icmp:
        filterLossy:
          baseline:
            sinks:
              *allSinks
            config:
              threshold: 30
          changepoint:
            sinks:
              *allSinks
          distdiff:
            sinks:
              *allSinks
          mode:
            sinks:
              *allSinks
          spike:
            sinks:
              *allSinks
          notADetector:
            sinks:
              *allSinks
      dns:
        loss:
          sinks:
            *allSinks
      notAType:
        loss:
          sinks:
            *allSinks

