# This file contains general settings that don't fit in other files.

caching:
  ttl: 30
  memcached:
    serverName: localhost
    port: 11211
    enabled: false

flink:
  maxLateness: 20
  checkpointInterval: 600

eventGrouping:
  graph:
    pruneIntervalCount: 500
    pruneIntervalTime: 43200 # 12 hours
    pruneAge: 1200
    exportInterval: 10
    exportLocation: /tmp/graph-export.dot
  time:
    maximumEventLength: 60
    maximumEventInterval: 10
