name: build-artifacts
on:
  pull_request:
  push:
  create:
    tags:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Scala environment
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11

      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2/repository
            ~/.sbt
          key: streamevmon-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y dpkg-dev dpkg-sig lintian

      - name: Package as .jar and .deb
        run: sbt update clean debian:packageBin

      - name: Upload .jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: streamevmon-projectAndNonProvidedDeps
          path: target/scala-2.12/streamevmon-projectAndNonProvidedDeps-*.jar

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: streamevmon-deb
          path: target/streamevmon_*.deb

      - name: Prepare directory for Cloudsmith (if running because of a tag)
        if: github.event_name == 'create'
        run: |
          mkdir -p packages/any-distro_any-version
          mv target/streamevmon_*.deb packages/any-distro_any-version

      - name: Upload to Cloudsmith (if running because of a tag)
        if: github.event_name == 'create'
        uses: wanduow/action-cloudsmith-upload-packages@v1
        with:
          path: packages/
          repo: ${{ secrets.CLOUDSMITH_OWNER }}/streamevmon
          username: ${{ secrets.CLOUDSMITH_USERNAME }}
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
