name: build-artifacts
on: [
    pull_request,
    push
]
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2/repository
            ~/.sbt
          key: streamevmon-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
      - run: sudo apt install -y dpkg-dev dpkg-sig lintian
      - run: sbt update clean debian:packageBin
      - uses: actions/upload-artifact@v2
        with:
          name: streamevmon-projectAndNonProvidedDeps
          path: target/scala-2.12/streamevmon-projectAndNonProvidedDeps-*.jar
      - uses: actions/upload-artifact@v2
        with:
          name: streamevmon-deb
          path: target/streamevmon_*.deb
