name: scaladoc-to-gh-pages
on:
  push:
    branches:
      - master
jobs:
  scaladoc-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.m2/repository
            ~/.sbt
          key: streamevmon-${{ hashFiles('**/build.sbt', '**/Dependencies.scala') }}
      - run: sudo apt-get install -y graphviz
      - run: sbt doc
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: target/scala-2.12/api
